### ISSUE TITLE
sorry i noob

### ISSUE THREAD

**Issue by glot1k** [SergioPrinci/rococo#6]
hi there! Can I contact you in discord to solve my problems. (glotik#3692)

**Comment by SergioPrinci** [comment]
Please, describe me your problems here so that others can see

**Comment by glot1k** [comment]
Ok.
1) Can I make more than 100 cards (200 for example)
Sorry for stupid question, but i don't know how to activate the bot. When I try to run core.py I get this: ![IMG_20210911_214028.jpg](https://user-images.githubusercontent.com/90206784/132958118-79d88e9e-1dec-4b31-9476-9c5ac3e04201.jpg)
*In botdata I write "False" with F capital, but in console its written with small.
Thank you in advance!

**Comment by SergioPrinci** [comment]
Ok, sorry for the late answer, but I am the only one managing the project and I do not have much time these days, but here I am!
Sure, you can make a lot of cards, even thousands, the bot should be able to manage any number of cards.
Do you leave the space after the colons? maybe you don't, about the thing you read on the traceback, making it simple, the bot takes the value and puts everything in lowercase so that he parses the pieces of information in a better and faster way.

If you have any other doubt, tell me, I'll try to reach to you as fast as possible!

**Comment by glot1k** [comment]
so...
When i type
cardgame: False
![IMG_20210913_193132.jpg](https://user-images.githubusercontent.com/90206784/133122782-3906ea1f-39b2-49b7-ab00-8c48bdca65fa.jpg)
I get this:
![IMG_20210913_193344.jpg](https://user-images.githubusercontent.com/90206784/133122836-394fcfe0-7802-4c66-967b-0d950292ebe8.jpg)
I tried a lot of variants of writing this, but it doesn't work :(

**Comment by SergioPrinci** [comment]
Alright, i'll make a patch when i can, sorry for the bugs

**Comment by glot1k** [comment]
ok😉
